# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:cryptowallet
    driverClassName: org.h2.Driver
    username: dantas
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      logging:
        level.org.hibernate.type: trace