INSERT INTO digital_currency_acronym (name, description) VALUES ('ACMFT','AC Milan');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ADA','Cardano');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ALCX','Alchemix');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ALGO','Algorand');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ALICE','MyNeighborAlice');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ALLFT','Alliance');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ANKR','ANKR');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ARGFT','Argentine Football Association');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ASRFT','AS Roma');
INSERT INTO digital_currency_acronym (name, description) VALUES ('AXS','Axie Infinity');
INSERT INTO digital_currency_acronym (name, description) VALUES ('BARFT','FC Barcelona');
INSERT INTO digital_currency_acronym (name, description) VALUES ('BCH','Bitcoin Cash');
INSERT INTO digital_currency_acronym (name, description) VALUES ('BNT','BANCOR');
INSERT INTO digital_currency_acronym (name, description) VALUES ('BTC','Bitcoin');
INSERT INTO digital_currency_acronym (name, description) VALUES ('CITYFT','Manchester City FC');
INSERT INTO digital_currency_acronym (name, description) VALUES ('COMP','Compound');
INSERT INTO digital_currency_acronym (name, description) VALUES ('DOGE','Dogecoin');
INSERT INTO digital_currency_acronym (name, description) VALUES ('DOT','Polkadot');
INSERT INTO digital_currency_acronym (name, description) VALUES ('DYDX','dYdX');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ENS','Ethereum Name Service');
INSERT INTO digital_currency_acronym (name, description) VALUES ('ETH','Ethereum');
INSERT INTO digital_currency_acronym (name, description) VALUES ('INTERFT','Inter Milan');
INSERT INTO digital_currency_acronym (name, description) VALUES ('JUVFT','Juventus');
INSERT INTO digital_currency_acronym (name, description) VALUES ('LPT','Livepeer');
INSERT INTO digital_currency_acronym (name, description) VALUES ('LRC','Loopring');
INSERT INTO digital_currency_acronym (name, description) VALUES ('MBPRK05','Fluxo de Pagamentos 5');
INSERT INTO digital_currency_acronym (name, description) VALUES ('MBPRK06','Precatorio MB BR06');
INSERT INTO digital_currency_acronym (name, description) VALUES ('MBSANTOS01','Token da Vila');
INSERT INTO digital_currency_acronym (name, description) VALUES ('MBVASCO01','Vasco Token');
INSERT INTO digital_currency_acronym (name, description) VALUES ('MCO2','Moss Carbon Credit');
INSERT INTO digital_currency_acronym (name, description) VALUES ('MENGOFT','Flamengo');
INSERT INTO digital_currency_acronym (name, description) VALUES ('MKR','Maker');
INSERT INTO digital_currency_acronym (name, description) VALUES ('NAVIFT','Natus Vincere');
INSERT INTO digital_currency_acronym (name, description) VALUES ('OGFT','OG eSports');
INSERT INTO digital_currency_acronym (name, description) VALUES ('OMG','Omg Network');
INSERT INTO digital_currency_acronym (name, description) VALUES ('PAXG','PAX Gold');
INSERT INTO digital_currency_acronym (name, description) VALUES ('PFLFT','Professional Fighters League');
INSERT INTO digital_currency_acronym (name, description) VALUES ('PORFT','Portugal National Team FT');
INSERT INTO digital_currency_acronym (name, description) VALUES ('PSGFT','Paris Saint-Germain');
INSERT INTO digital_currency_acronym (name, description) VALUES ('QNT','Quant');
INSERT INTO digital_currency_acronym (name, description) VALUES ('RACA','Radio Caca');
INSERT INTO digital_currency_acronym (name, description) VALUES ('RAD','Radicle');
INSERT INTO digital_currency_acronym (name, description) VALUES ('REN','Ren');
INSERT INTO digital_currency_acronym (name, description) VALUES ('REQ','Request');
INSERT INTO digital_currency_acronym (name, description) VALUES ('SAND','The Sandbox');
INSERT INTO digital_currency_acronym (name, description) VALUES ('SAUBERFT','Alfa Romeo Racing ORLEN');
INSERT INTO digital_currency_acronym (name, description) VALUES ('SCCPFT','Corinthians');
INSERT INTO digital_currency_acronym (name, description) VALUES ('SHIB','Shiba Inu');
INSERT INTO digital_currency_acronym (name, description) VALUES ('SLP','Smooth Love Potion');
INSERT INTO digital_currency_acronym (name, description) VALUES ('SOL','Solana');
